import type { VfThemePreset } from '@/types/theme'
import breakpoints from '@/foundation/breakpoints.json'

const breakpointTokens = {
  breakpointXs: `${breakpoints.xs}px`,
  breakpointSm: `${breakpoints.sm}px`,
  breakpointMd: `${breakpoints.md}px`,
  breakpointLg: `${breakpoints.lg}px`,
  breakpointXl: `${breakpoints.xl}px`,
  breakpoint2xl: `${breakpoints['2xl']}px`
}

export const defaultThemePreset: VfThemePreset = {
  name: 'vueforge-default',
  tokens: {
    colorBg: '#fcfcfd',
    colorSurface: '#ffffff',
    colorSurfaceMuted: '#f5f7fb',
    colorText: '#172033',
    colorMuted: '#69738a',
    colorBorder: '#d8e0ef',
    colorPrimary: '#0b63f6',
    colorPrimaryContrast: '#ffffff',
    colorPrimarySoft: 'color-mix(in srgb, var(--vf-color-primary) 12%, var(--vf-color-surface))',
    colorPrimaryBorderSoft: 'color-mix(in srgb, var(--vf-color-primary) 22%, var(--vf-color-border))',
    colorFocusRing: 'color-mix(in srgb, var(--vf-color-primary) 52%, var(--vf-color-surface))',
    colorSuccess: '#16a34a',
    colorDanger: '#dc2626',
    colorSuccessSoft: 'color-mix(in srgb, var(--vf-color-success) 12%, var(--vf-color-surface))',
    colorDangerSoft: 'color-mix(in srgb, var(--vf-color-danger) 12%, var(--vf-color-surface))',
    colorSuccessBorderSoft: 'color-mix(in srgb, var(--vf-color-success) 24%, var(--vf-color-border))',
    colorDangerBorderSoft: 'color-mix(in srgb, var(--vf-color-danger) 24%, var(--vf-color-border))',
    radius: '0.75rem',
    radiusControl: 'calc(var(--vf-radius) - 0.125rem)',
    radiusControlTight: 'calc(var(--vf-radius) - 0.25rem)',
    radiusSurface: 'var(--vf-radius)',
    radiusOverlay: 'calc(var(--vf-radius) + 0.125rem)',
    ...breakpointTokens,
    controlHeightSm: '1.75rem',
    controlHeightMd: '2.25rem',
    controlHeightLg: '2.5rem',
    controlFontSizeSm: '0.875rem',
    controlFontSizeMd: '0.9375rem',
    controlFontSizeLg: '1rem',
    buttonPaddingSm: '0.25rem 0.55rem',
    buttonPaddingMd: '0.375rem 0.75rem',
    buttonPaddingLg: '0.5rem 0.875rem',
    buttonGap: '0.5rem',
    fieldPaddingSm: '0.25rem 0.55rem',
    fieldPaddingMd: '0.375rem 0.65rem',
    fieldPaddingLg: '0.5rem 0.75rem',
    textareaMinHeightSm: '4.5rem',
    textareaMinHeightMd: '6rem',
    textareaMinHeightLg: '7rem',
    overlayPadding: '0.875rem',
    overlayGap: '0.75rem',
    overlayViewportPadding: '1rem',
    menuPadding: '0.4rem',
    menuGap: '0.2rem',
    menuMinWidth: '12rem',
    surfacePadding: '0.95rem',
    surfaceGap: '0.625rem',
    surfacePaddingCompact: '0.7rem',
    surfaceGapCompact: '0.5rem',
    sectionPadding: '0.75rem 0.9rem',
    sectionGap: '0.75rem',
    tabsGap: '0.875rem',
    tabsListGap: '0.375rem',
    tabsListPadding: '0.25rem',
    tabsTabPaddingInline: '0.8rem',
    tabsPanelPaddingTop: '0.75rem',
    badgeHeight: '1.625rem',
    badgePadding: '0.2rem 0.55rem',
    badgeGap: '0.375rem',
    badgeRadius: '999px',
    badgeFontSize: '0.8125rem',
    badgeLineHeight: '1.2',
    tagHeight: '1.75rem',
    tagPadding: '0.25rem 0.6rem',
    tagFontSize: '0.8125rem',
    tagLineHeight: '1.2',
    tooltipPadding: '0.45rem 0.65rem',
    tooltipMaxWidth: '16rem',
    tooltipFontSize: '0.8125rem',
    tooltipLineHeight: '1.4',
    dialogWidthSm: '28rem',
    dialogWidthMd: '36rem',
    dialogWidthLg: '48rem',
    dialogMaxHeight: 'min(85vh, 48rem)',
    dialogTitleFontSize: '1.125rem',
    dialogHeaderGap: '0.75rem',
    dialogActionsGap: '0.5rem',
    popoverWidth: 'min(100vw - 2rem, 22rem)',
    floatingArrowSize: '0.625rem',
    overlayBackdrop: 'rgba(15, 23, 42, 0.56)',
    overlayBackdropBlur: '6px',
    alertPrimarySoft: 'color-mix(in srgb, var(--vf-color-primary) 8%, var(--vf-color-surface))',
    alertPrimaryBorderSoft: 'color-mix(in srgb, var(--vf-color-primary) 22%, var(--vf-color-border))',
    alertContentGap: '0.25rem',
    alertTitleFontSize: '0.9375rem',
    cardTitleFontSize: '1rem',
    panelTitleFontSize: '0.9375rem',
    textLineHeight: '1.5',
    headingLineHeight: '1.3',
    tabsLineHeight: '1.2',
    spacing: '1rem',
    shadow: 'none'
  },
  dark: {
    colorBg: '#0f172a',
    colorSurface: '#162033',
    colorSurfaceMuted: '#1b2840',
    colorText: '#eff4ff',
    colorMuted: '#9fb0cf',
    colorBorder: '#2d405f',
    colorPrimary: '#6ea8fe',
    colorPrimaryContrast: '#081120',
    colorPrimarySoft: 'color-mix(in srgb, var(--vf-color-primary) 12%, var(--vf-color-surface))',
    colorPrimaryBorderSoft: 'color-mix(in srgb, var(--vf-color-primary) 22%, var(--vf-color-border))',
    colorFocusRing: 'color-mix(in srgb, var(--vf-color-primary) 52%, var(--vf-color-surface))',
    colorSuccess: '#4ade80',
    colorDanger: '#f87171',
    colorSuccessSoft: 'color-mix(in srgb, var(--vf-color-success) 12%, var(--vf-color-surface))',
    colorDangerSoft: 'color-mix(in srgb, var(--vf-color-danger) 12%, var(--vf-color-surface))',
    colorSuccessBorderSoft: 'color-mix(in srgb, var(--vf-color-success) 24%, var(--vf-color-border))',
    colorDangerBorderSoft: 'color-mix(in srgb, var(--vf-color-danger) 24%, var(--vf-color-border))',
    shadow: 'none'
  }
}
