import breakpoints from "../foundation/breakpoints.json";
import { vfMotionTokens } from "@codemonster-ru/vueforge-theme";

export const breakpointTokens = {
  breakpointXs: `${breakpoints.xs}px`,
  breakpointSm: `${breakpoints.sm}px`,
  breakpointMd: `${breakpoints.md}px`,
  breakpointLg: `${breakpoints.lg}px`,
  breakpointXl: `${breakpoints.xl}px`,
  breakpoint2xl: `${breakpoints["2xl"]}px`,
};

export const defaultThemePresetSource = {
  name: "vueforge-default",
  tokens: {
    fontFamilyBase:
      'ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif',
    fontFamilyHeading:
      'ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif',
    fontFamilyMono:
      'ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, "Liberation Mono", monospace',
    fontWeightRegular: "400",
    fontWeightMedium: "500",
    fontWeightSemibold: "600",
    fontWeightBold: "700",
    fontSizeXs: "0.75rem",
    fontSizeSm: "0.8125rem",
    fontSizeMd: "0.875rem",
    fontSizeLg: "0.9375rem",
    fontSizeXl: "1rem",
    fontSize2xl: "1.125rem",
    fontSize3xl: "1.25rem",
    lineHeightTight: "1.2",
    lineHeightNormal: "1.5",
    lineHeightRelaxed: "1.65",
    textBodyFontSize: "var(--vf-font-size-xl)",
    textBodyLineHeight: "var(--vf-line-height-normal)",
    textBodyFontWeight: "var(--vf-font-weight-regular)",
    textCaptionFontSize: "var(--vf-font-size-sm)",
    textCaptionLineHeight: "var(--vf-line-height-normal)",
    textCaptionFontWeight: "var(--vf-font-weight-medium)",
    textLabelFontSize: "var(--vf-font-size-md)",
    textLabelLineHeight: "var(--vf-line-height-tight)",
    textLabelFontWeight: "var(--vf-font-weight-medium)",
    headingFontSizeSm: "var(--vf-font-size-lg)",
    headingFontSizeMd: "var(--vf-font-size-xl)",
    headingFontSizeLg: "var(--vf-font-size-2xl)",
    headingFontSizeXl: "var(--vf-font-size-3xl)",
    headingFontWeight: "var(--vf-font-weight-semibold)",
    buttonSecondaryHoverBackground:
      "color-mix(in srgb, var(--vf-color-surface-muted) 92%, var(--vf-color-text))",
    buttonSecondaryHoverBorderColor: "var(--vf-color-border)",
    buttonGhostHoverBackground: "var(--vf-color-surface-muted)",
    buttonGhostHoverBorderColor: "transparent",
    buttonPrimaryHoverFilter: "brightness(0.96)",
    buttonSuccessHoverFilter: "brightness(0.96)",
    buttonInfoHoverFilter: "brightness(0.96)",
    buttonWarnHoverFilter: "brightness(0.96)",
    buttonHelpHoverFilter: "brightness(0.96)",
    buttonDangerHoverFilter: "brightness(0.96)",
    buttonContrastHoverFilter: "brightness(0.96)",
    radioControlBackground:
      "color-mix(in srgb, var(--vf-color-border) 12%, var(--vf-color-surface))",
    radioHoverBorderColor: "var(--vf-color-primary-border-soft)",
    switchTrackBackground:
      "color-mix(in srgb, var(--vf-color-text) 10%, var(--vf-color-surface))",
    switchTrackHoverBackground:
      "color-mix(in srgb, var(--vf-color-text) 12%, var(--vf-color-surface))",
    switchTrackCheckedBackground: "var(--vf-color-primary)",
    switchTrackCheckedHoverBackground:
      "color-mix(in srgb, var(--vf-color-primary) 92%, var(--vf-color-surface))",
    switchThumbBackground:
      "color-mix(in srgb, var(--vf-color-surface) 88%, var(--vf-color-surface-muted))",
    switchThumbBorderColor:
      "color-mix(in srgb, var(--vf-color-surface) 80%, var(--vf-color-border))",
    switchThumbShadow:
      "0 1px 2px color-mix(in srgb, var(--vf-color-text) 18%, transparent)",
    switchThumbColor:
      "color-mix(in srgb, var(--vf-color-text) 55%, transparent)",
    switchThumbIconSize: "0.625rem",
    switchThumbCheckedBackground: "var(--vf-color-surface)",
    switchThumbCheckedBorderColor:
      "color-mix(in srgb, var(--vf-color-primary) 12%, var(--vf-color-surface))",
    switchThumbCheckedShadow:
      "0 1px 1.5px color-mix(in srgb, var(--vf-color-text) 12%, transparent)",
    proseHeadingMargin: "1.5em",
    proseHeadingGap: "0.5em",
    proseBlockSpacing: "1em",
    proseListPaddingInlineStart: "1.5em",
    proseListItemSpacing: "0.375em",
    proseLinkHoverColor:
      "color-mix(in srgb, var(--vf-color-primary) 82%, var(--vf-color-text))",
    proseBlockquotePaddingInlineStart: "1rem",
    proseBlockquoteBorderWidth: "3px",
    proseInlineCodeFontSize: "0.95em",
    proseInlineCodePadding: "0.125rem 0.375rem",
    proseCodeBlockPadding: "0.75rem 1rem",
    proseHrMargin: "1.5rem",
    colorBg: "#fcfcfd",
    colorSurface: "#ffffff",
    colorSurfaceMuted: "#f5f7fb",
    colorText: "#172033",
    colorMuted: "#69738a",
    colorBorder: "#d8e0ef",
    colorPrimary: "#0b63f6",
    colorPrimaryContrast: "#ffffff",
    colorPrimarySoft:
      "color-mix(in srgb, var(--vf-color-primary) 12%, var(--vf-color-surface))",
    colorPrimaryBorderSoft:
      "color-mix(in srgb, var(--vf-color-primary) 22%, var(--vf-color-border))",
    colorFocusRing:
      "color-mix(in srgb, var(--vf-color-primary) 32%, var(--vf-color-surface))",
    colorSuccess: "#16a34a",
    colorSuccessContrast: "#ffffff",
    colorInfo: "#0ea5e9",
    colorInfoContrast: "#ffffff",
    colorWarn: "#f59e0b",
    colorWarnContrast: "#1f1300",
    colorHelp: "#8b5cf6",
    colorHelpContrast: "#ffffff",
    colorDanger: "#dc2626",
    colorDangerContrast: "#ffffff",
    colorContrast: "#111827",
    colorContrastContrast: "#ffffff",
    colorSuccessSoft:
      "color-mix(in srgb, var(--vf-color-success) 12%, var(--vf-color-surface))",
    colorInfoSoft:
      "color-mix(in srgb, var(--vf-color-info) 12%, var(--vf-color-surface))",
    colorWarnSoft:
      "color-mix(in srgb, var(--vf-color-warn) 12%, var(--vf-color-surface))",
    colorHelpSoft:
      "color-mix(in srgb, var(--vf-color-help) 12%, var(--vf-color-surface))",
    colorDangerSoft:
      "color-mix(in srgb, var(--vf-color-danger) 12%, var(--vf-color-surface))",
    colorContrastSoft:
      "color-mix(in srgb, var(--vf-color-contrast) 10%, var(--vf-color-surface))",
    colorSuccessBorderSoft:
      "color-mix(in srgb, var(--vf-color-success) 24%, var(--vf-color-border))",
    colorInfoBorderSoft:
      "color-mix(in srgb, var(--vf-color-info) 24%, var(--vf-color-border))",
    colorWarnBorderSoft:
      "color-mix(in srgb, var(--vf-color-warn) 24%, var(--vf-color-border))",
    colorHelpBorderSoft:
      "color-mix(in srgb, var(--vf-color-help) 24%, var(--vf-color-border))",
    colorDangerBorderSoft:
      "color-mix(in srgb, var(--vf-color-danger) 24%, var(--vf-color-border))",
    colorContrastBorderSoft:
      "color-mix(in srgb, var(--vf-color-contrast) 24%, var(--vf-color-border))",
    focusRingWidth: "3px",
    radius: "0.75rem",
    radiusControl: "calc(var(--vf-radius) - 0.125rem)",
    radiusControlTight: "calc(var(--vf-radius) - 0.25rem)",
    radiusSurface: "var(--vf-radius)",
    radiusOverlay: "calc(var(--vf-radius) + 0.125rem)",
    ...breakpointTokens,
    controlHeightSm: "1.75rem",
    controlHeightMd: "2.25rem",
    controlHeightLg: "2.5rem",
    controlFontSizeSm: "var(--vf-font-size-md)",
    controlFontSizeMd: "var(--vf-font-size-lg)",
    controlFontSizeLg: "var(--vf-font-size-xl)",
    buttonPaddingSm: "0.25rem 0.5rem",
    buttonPaddingMd: "0.375rem 0.75rem",
    buttonPaddingLg: "0.5rem 1rem",
    buttonGap: "0.5rem",
    fieldPaddingSm: "0.25rem 0.5rem",
    fieldPaddingMd: "0.375rem 0.75rem",
    fieldPaddingLg: "0.5rem 1rem",
    checkboxSizeSm: "1rem",
    checkboxSizeMd: "1.125rem",
    checkboxSizeLg: "1.25rem",
    selectionGap: "0.75rem",
    checkboxMarkWidth: "0.25rem",
    checkboxMarkHeight: "0.5rem",
    checkboxMarkStrokeWidth: "2px",
    checkboxMarkOffsetY: "-0.0625rem",
    radioDotSize: "0.5rem",
    switchWidthSm: "2rem",
    switchWidthMd: "2.25rem",
    switchWidthLg: "2.5rem",
    switchHeightSm: "1.125rem",
    switchHeightMd: "1.25rem",
    switchHeightLg: "1.375rem",
    switchThumbSizeSm: "0.75rem",
    switchThumbSizeMd: "0.875rem",
    switchThumbSizeLg: "1rem",
    switchThumbInset: "0.125rem",
    textareaMinHeightSm: "4.5rem",
    textareaMinHeightMd: "6rem",
    textareaMinHeightLg: "7rem",
    overlayPadding: "1rem",
    overlayGap: "0.75rem",
    overlayViewportPadding: "1rem",
    menuPadding: "0.5rem",
    menuGap: "0.25rem",
    menuMinWidth: "12rem",
    surfacePadding: "1rem",
    surfaceGap: "0.75rem",
    surfacePaddingCompact: "0.75rem",
    surfaceGapCompact: "0.5rem",
    sectionPadding: "0.75rem 1rem",
    sectionGap: "0.75rem",
    tabsGap: "0.75rem",
    tabsListGap: "0.25rem",
    tabsListPadding: "0.25rem",
    tabsTabPaddingInline: "0.75rem",
    tabsPanelPaddingTop: "0.75rem",
    navMenuListGap: "0.25rem",
    navMenuNestedGap: "0.25rem",
    navMenuCollapseOffsetTop: "0.25rem",
    navMenuCollapseInsetLevel0Margin: "0.5rem",
    navMenuCollapseInsetLevel0Padding: "0.5rem",
    navMenuCollapseInsetSimpleLevel0Margin: "0.5rem",
    navMenuCollapseInsetSimpleLevel0Padding: "0.5rem",
    navMenuCollapseInsetDeepMargin: "0.5rem",
    navMenuCollapseInsetDeepPadding: "0.5rem",
    navMenuCollapseInsetSimpleDeepMargin: "0.5rem",
    navMenuCollapseInsetSimpleDeepPadding: "0.5rem",
    navMenuNodeGroupSpacing: "0.25rem",
    navMenuGroupPadding: "0.375rem 0.75rem",
    navMenuGroupFontSize: "var(--vf-text-label-font-size)",
    navMenuItemPadding: "0.375rem 0.75rem",
    navMenuItemGap: "0.5rem",
    navMenuLeadingIconSize: "1rem",
    navMenuLeadingIconColumnSize: "1.25rem",
    tableOfContentsGap: "0.25rem",
    tableOfContentsListGap: "var(--vf-nav-menu-list-gap)",
    tableOfContentsTitleFontSize: "var(--vf-text-caption-font-size)",
    tableOfContentsTitleColor: "var(--vf-color-muted)",
    tableOfContentsItemPadding: "var(--vf-nav-menu-item-padding)",
    tableOfContentsLevelStep: "0.5rem",
    tableOfContentsColor: "var(--vf-color-text)",
    tableOfContentsHoverColor: "var(--vf-color-primary)",
    tableOfContentsHoverBackground:
      "color-mix(in srgb, var(--vf-color-primary) 10%, var(--vf-color-surface))",
    tableOfContentsActiveColor: "var(--vf-color-primary)",
    tableOfContentsActiveBackground:
      "color-mix(in srgb, var(--vf-color-primary) 14%, var(--vf-color-surface))",
    badgeHeight: "1.5rem",
    badgePadding: "0.25rem 0.5rem",
    badgeGap: "0.25rem",
    badgeRadius: "999px",
    badgeFontSize: "var(--vf-text-caption-font-size)",
    badgeLineHeight: "var(--vf-text-caption-line-height)",
    tagHeight: "1.75rem",
    tagPadding: "0.25rem 0.5rem",
    tagFontSize: "var(--vf-text-caption-font-size)",
    tagLineHeight: "var(--vf-text-caption-line-height)",
    tooltipPadding: "0.5rem 0.75rem",
    tooltipMaxWidth: "16rem",
    tooltipFontSize: "var(--vf-text-caption-font-size)",
    tooltipLineHeight: "var(--vf-text-caption-line-height)",
    dialogWidthSm: "28rem",
    dialogWidthMd: "36rem",
    dialogWidthLg: "48rem",
    dialogMaxHeight: "min(85vh, 48rem)",
    drawerSizeSm: "20rem",
    drawerSizeMd: "26rem",
    drawerSizeLg: "32rem",
    drawerOffsetTop: "0px",
    drawerBodyPadding: "var(--vf-overlay-padding)",
    dialogTitleFontSize: "var(--vf-heading-font-size-lg)",
    dialogHeaderGap: "0.75rem",
    dialogActionsGap: "0.5rem",
    popoverWidth: "min(100vw - 2rem, 22rem)",
    floatingArrowSize: "0.625rem",
    overlayBackdrop: "rgba(15, 23, 42, 0.56)",
    alertPrimarySoft:
      "color-mix(in srgb, var(--vf-color-primary) 8%, var(--vf-color-surface))",
    alertPrimaryBorderSoft:
      "color-mix(in srgb, var(--vf-color-primary) 22%, var(--vf-color-border))",
    alertContentGap: "0.25rem",
    alertTitleFontSize: "var(--vf-heading-font-size-sm)",
    cardTitleFontSize: "var(--vf-heading-font-size-md)",
    panelTitleFontSize: "var(--vf-heading-font-size-sm)",
    textLineHeight: "var(--vf-text-body-line-height)",
    headingLineHeight: "var(--vf-line-height-tight)",
    tabsLineHeight: "1.2",
    motionDurationFast: vfMotionTokens.durationFast,
    motionDurationNormal: vfMotionTokens.durationNormal,
    motionEaseStandard: vfMotionTokens.easeStandard,
    zOverlay: "1000",
    zDrawer: "1000",
    zDropdown: "900",
    zPopover: "925",
    zTooltip: "950",
    spacing: "1rem",
    shadow: "none",
  },
  dark: {
    colorBg: "#0f172a",
    colorSurface: "#162033",
    colorSurfaceMuted: "#1b2840",
    colorText: "#eff4ff",
    colorMuted: "#9fb0cf",
    colorBorder: "#2d405f",
    colorPrimary: "#6ea8fe",
    colorPrimaryContrast: "#081120",
    colorPrimarySoft:
      "color-mix(in srgb, var(--vf-color-primary) 12%, var(--vf-color-surface))",
    colorPrimaryBorderSoft:
      "color-mix(in srgb, var(--vf-color-primary) 22%, var(--vf-color-border))",
    colorFocusRing:
      "color-mix(in srgb, var(--vf-color-primary) 32%, var(--vf-color-surface))",
    colorSuccess: "#4ade80",
    colorSuccessContrast: "#081120",
    colorInfo: "#38bdf8",
    colorInfoContrast: "#081120",
    colorWarn: "#fbbf24",
    colorWarnContrast: "#1f1300",
    colorHelp: "#a78bfa",
    colorHelpContrast: "#081120",
    colorDanger: "#f87171",
    colorDangerContrast: "#081120",
    colorContrast: "#f3f4f6",
    colorContrastContrast: "#111827",
    colorSuccessSoft:
      "color-mix(in srgb, var(--vf-color-success) 12%, var(--vf-color-surface))",
    colorInfoSoft:
      "color-mix(in srgb, var(--vf-color-info) 12%, var(--vf-color-surface))",
    colorWarnSoft:
      "color-mix(in srgb, var(--vf-color-warn) 12%, var(--vf-color-surface))",
    colorHelpSoft:
      "color-mix(in srgb, var(--vf-color-help) 12%, var(--vf-color-surface))",
    colorDangerSoft:
      "color-mix(in srgb, var(--vf-color-danger) 12%, var(--vf-color-surface))",
    colorContrastSoft:
      "color-mix(in srgb, var(--vf-color-contrast) 10%, var(--vf-color-surface))",
    colorSuccessBorderSoft:
      "color-mix(in srgb, var(--vf-color-success) 24%, var(--vf-color-border))",
    colorInfoBorderSoft:
      "color-mix(in srgb, var(--vf-color-info) 24%, var(--vf-color-border))",
    colorWarnBorderSoft:
      "color-mix(in srgb, var(--vf-color-warn) 24%, var(--vf-color-border))",
    colorHelpBorderSoft:
      "color-mix(in srgb, var(--vf-color-help) 24%, var(--vf-color-border))",
    colorDangerBorderSoft:
      "color-mix(in srgb, var(--vf-color-danger) 24%, var(--vf-color-border))",
    colorContrastBorderSoft:
      "color-mix(in srgb, var(--vf-color-contrast) 24%, var(--vf-color-border))",
    focusRingWidth: "3px",
    zOverlay: "1000",
    zDrawer: "1000",
    zDropdown: "900",
    zPopover: "925",
    zTooltip: "950",
    shadow: "none",
  },
};
