import breakpoints from "../foundation/breakpoints.json";
import { vfMotionTokens } from "@codemonster-ru/vueforge-theme";

export const breakpointTokens = {
  breakpointXs: `${breakpoints.xs}px`,
  breakpointSm: `${breakpoints.sm}px`,
  breakpointMd: `${breakpoints.md}px`,
  breakpointLg: `${breakpoints.lg}px`,
  breakpointXl: `${breakpoints.xl}px`,
  breakpoint2xl: `${breakpoints["2xl"]}px`,
};

export const defaultThemePresetSource = {
  name: "vueforge-default",
  tokens: {
    fontFamilyBase:
      'Inter, ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif',
    fontFamilyHeading:
      'Inter, ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif',
    fontFamilyMono:
      'ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, "Liberation Mono", monospace',
    fontWeightRegular: "400",
    fontWeightMedium: "500",
    fontWeightSemibold: "600",
    fontWeightBold: "700",
    fontSizeXs: "0.75rem",
    fontSizeSm: "0.8125rem",
    fontSizeMd: "0.875rem",
    fontSizeLg: "0.9375rem",
    fontSizeXl: "1rem",
    fontSize2xl: "1.125rem",
    fontSize3xl: "1.25rem",
    lineHeightTight: "1.2",
    lineHeightNormal: "1.5",
    lineHeightRelaxed: "1.65",
    selectableHoverColor: "var(--vf-color-primary)",
    selectableHoverBackground: "transparent",
    selectableActiveColor: "var(--vf-color-primary)",
    selectableActiveBackground:
      "color-mix(in srgb, var(--vf-color-primary) 20%, var(--vf-color-surface))",
    navMenuItemHoverColor: "var(--vf-color-primary)",
    navMenuItemHoverBackground: "transparent",
    navMenuItemActiveColor: "var(--vf-color-primary)",
    navMenuItemActiveBackground: "transparent",
    navMenuPillsItemPadding: "var(--vf-field-padding-md)",
    navMenuPillsListGap: "var(--vf-nav-menu-list-gap)",
    navMenuPillsNestedGap: "var(--vf-nav-menu-nested-gap)",
    navMenuPillsCollapseOffsetTop: "var(--vf-nav-menu-collapse-offset-top)",
    navMenuPillsItemMinHeight: "var(--vf-control-height-md)",
    navMenuPillsItemHoverColor: "var(--vf-selectable-hover-color)",
    navMenuPillsItemHoverBackground:
      "color-mix(in srgb, var(--vf-color-primary) 5%, transparent)",
    navMenuPillsItemActiveColor: "var(--vf-selectable-active-color)",
    navMenuPillsItemActiveBackground: "var(--vf-selectable-active-background)",
    navMenuGroupLabelColor:
      "color-mix(in srgb, var(--vf-color-muted) 90%, var(--vf-color-text))",
    navMenuItemColor: "var(--vf-color-text)",
    navMenuItemRadius: "var(--vf-radius-control)",
    navMenuItemFocusColor: "var(--vf-color-primary)",
    navMenuItemFocusBorderColor: "var(--vf-color-primary)",
    navMenuItemAncestorActiveColor: "var(--vf-color-primary)",
    navMenuBranchColor: "var(--vf-color-text)",
    navMenuBranchAncestorActiveColor:
      "var(--vf-nav-menu-item-ancestor-active-color)",
    tableOfContentsPillsListGap: "var(--vf-table-of-contents-list-gap)",
    tableOfContentsPillsItemPadding: "0.25rem 0.625rem",
    tableOfContentsPillsItemMinHeight: "2rem",
    tableOfContentsPillsHoverColor: "var(--vf-table-of-contents-hover-color)",
    tableOfContentsPillsHoverBackground:
      "color-mix(in srgb, var(--vf-color-primary) 5%, transparent)",
    tableOfContentsPillsActiveColor: "var(--vf-table-of-contents-active-color)",
    tableOfContentsPillsActiveBackground:
      "var(--vf-table-of-contents-active-background)",
    menuBarPillsSubmenuHoverBackground:
      "color-mix(in srgb, var(--vf-color-primary) 5%, transparent)",
    menuBarPillsSubmenuActiveBackground:
      "var(--vf-selectable-active-background)",
    menuBarPillsListGap: "var(--vf-nav-menu-list-gap)",
    menuBarItemColor: "var(--vf-color-text)",
    menuBarItemFocusColor: "var(--vf-color-primary)",
    menuBarItemFocusBorderColor: "var(--vf-color-primary)",
    menuBarItemAncestorActiveColor: "var(--vf-selectable-active-color)",
    menuBarTopHoverColor: "var(--vf-nav-menu-item-hover-color)",
    menuBarTopHoverBackground: "var(--vf-nav-menu-item-hover-background)",
    menuBarTopActiveColor: "var(--vf-nav-menu-item-active-color)",
    menuBarTopActiveBackground: "var(--vf-nav-menu-item-active-background)",
    menuBarSubmenuHoverColor: "var(--vf-nav-menu-item-hover-color)",
    menuBarSubmenuHoverBackground: "var(--vf-nav-menu-item-hover-background)",
    menuBarSubmenuActiveColor: "var(--vf-nav-menu-item-active-color)",
    menuBarSubmenuActiveBackground: "var(--vf-nav-menu-item-active-background)",
    menuBarPillsTopHoverColor: "var(--vf-nav-menu-pills-item-hover-color)",
    menuBarPillsTopHoverBackground:
      "var(--vf-nav-menu-pills-item-hover-background)",
    menuBarPillsTopActiveColor: "var(--vf-nav-menu-pills-item-active-color)",
    menuBarPillsTopActiveBackground:
      "var(--vf-nav-menu-pills-item-active-background)",
    menuBarPillsSubmenuHoverColor: "var(--vf-nav-menu-pills-item-hover-color)",
    menuBarPillsSubmenuActiveColor:
      "var(--vf-nav-menu-pills-item-active-color)",
    tableOfContentsFocusColor: "var(--vf-color-primary)",
    tableOfContentsFocusBorderColor: "var(--vf-color-primary)",
    dropdownItemColor: "var(--vf-color-text)",
    dropdownItemFocusColor: "var(--vf-color-primary)",
    dropdownItemFocusBorderColor: "var(--vf-color-primary)",
    dropdownItemDefaultHoverColor: "var(--vf-nav-menu-item-hover-color)",
    dropdownItemDefaultHoverBackground:
      "var(--vf-nav-menu-item-hover-background)",
    dropdownItemDefaultActiveColor: "var(--vf-nav-menu-item-active-color)",
    dropdownItemDefaultActiveBackground:
      "var(--vf-nav-menu-item-active-background)",
    dropdownItemPillsHoverColor: "var(--vf-nav-menu-pills-item-hover-color)",
    dropdownItemPillsHoverBackground:
      "var(--vf-nav-menu-pills-item-hover-background)",
    dropdownItemPillsActiveColor: "var(--vf-nav-menu-pills-item-active-color)",
    dropdownItemPillsActiveBackground:
      "var(--vf-nav-menu-pills-item-active-background)",
    breadcrumbsLinkColor: "var(--vf-color-muted)",
    breadcrumbsLinkHoverColor: "var(--vf-selectable-hover-color)",
    breadcrumbsLinkFocusColor: "var(--vf-color-primary)",
    breadcrumbsCurrentColor: "var(--vf-color-text)",
    breadcrumbsDisabledColor: "var(--vf-color-muted)",
    breadcrumbsSeparatorColor: "var(--vf-color-muted)",
    accordionBorderColor: "var(--vf-color-border)",
    accordionBackground: "var(--vf-color-surface)",
    accordionColor: "var(--vf-color-text)",
    accordionTriggerExpandedColor: "var(--vf-selectable-active-color)",
    accordionTriggerHoverColor: "var(--vf-selectable-hover-color)",
    accordionTriggerFocusBorderColor: "var(--vf-color-primary)",
    accordionIconColor: "var(--vf-color-muted)",
    accordionContentBackground: "var(--vf-color-surface)",
    accordionContentBorderColor: "var(--vf-color-border)",
    accordionContentColor: "var(--vf-color-muted)",
    tabsListBorderColor: "var(--vf-color-border)",
    tabsTabColor: "var(--vf-color-text)",
    tabsTabHoverColor: "var(--vf-selectable-hover-color)",
    tabsTabActiveColor: "var(--vf-selectable-active-color)",
    tabsIndicatorColor: "var(--vf-color-primary)",
    tabsPanelColor: "var(--vf-color-text)",
    tabsPanelFocusBorderColor: "var(--vf-color-primary)",
    badgeBackground: "var(--vf-color-surface-muted)",
    badgeBorderColor: "var(--vf-color-border)",
    badgeColor: "var(--vf-color-text)",
    badgePrimaryBackground: "var(--vf-color-primary-soft)",
    badgePrimaryBorderColor: "var(--vf-color-primary)",
    badgePrimaryColor: "var(--vf-color-primary)",
    badgeSuccessBackground: "var(--vf-color-success-soft)",
    badgeSuccessBorderColor: "var(--vf-color-success)",
    badgeSuccessColor: "var(--vf-color-success)",
    badgeInfoBackground: "var(--vf-color-info-soft)",
    badgeInfoBorderColor: "var(--vf-color-info)",
    badgeInfoColor: "var(--vf-color-info)",
    badgeWarnBackground: "var(--vf-color-warn-soft)",
    badgeWarnBorderColor: "var(--vf-color-warn)",
    badgeWarnColor: "var(--vf-color-warn)",
    badgeHelpBackground: "var(--vf-color-help-soft)",
    badgeHelpBorderColor: "var(--vf-color-help)",
    badgeHelpColor: "var(--vf-color-help)",
    badgeDangerBackground: "var(--vf-color-danger-soft)",
    badgeDangerBorderColor: "var(--vf-color-danger)",
    badgeDangerColor: "var(--vf-color-danger)",
    badgeContrastBackground: "var(--vf-color-contrast-soft)",
    badgeContrastBorderColor: "var(--vf-color-contrast)",
    badgeContrastColor: "var(--vf-color-contrast)",
    tagBackground:
      "color-mix(in srgb, var(--vf-color-surface) 94%, var(--vf-color-surface-muted))",
    tagBorderColor: "var(--vf-color-border)",
    tagColor: "var(--vf-color-text)",
    tagPrimaryBorderColor: "var(--vf-color-primary)",
    tagPrimaryColor: "var(--vf-color-primary)",
    tagSuccessBorderColor: "var(--vf-color-success)",
    tagSuccessColor: "var(--vf-color-success)",
    tagInfoBorderColor: "var(--vf-color-info)",
    tagInfoColor: "var(--vf-color-info)",
    tagWarnBorderColor: "var(--vf-color-warn)",
    tagWarnColor: "var(--vf-color-warn)",
    tagHelpBorderColor: "var(--vf-color-help)",
    tagHelpColor: "var(--vf-color-help)",
    tagDangerBorderColor: "var(--vf-color-danger)",
    tagDangerColor: "var(--vf-color-danger)",
    tagContrastBorderColor: "var(--vf-color-contrast)",
    tagContrastColor: "var(--vf-color-contrast)",
    alertColor: "var(--vf-color-text)",
    alertBodyColor:
      "color-mix(in srgb, var(--vf-color-muted) 92%, var(--vf-color-text))",
    alertPrimaryIconColor: "var(--vf-color-primary)",
    alertSuccessIconColor: "var(--vf-color-success)",
    alertInfoIconColor: "var(--vf-color-info)",
    alertWarnIconColor: "var(--vf-color-warn)",
    alertHelpIconColor: "var(--vf-color-help)",
    alertDangerIconColor: "var(--vf-color-danger)",
    alertContrastIconColor: "var(--vf-color-contrast)",
    dividerColor: "var(--vf-color-border)",
    cardBorderColor: "var(--vf-color-border)",
    cardBackground: "var(--vf-color-surface)",
    cardColor: "var(--vf-color-text)",
    cardBodyColor: "var(--vf-color-muted)",
    panelBorderColor: "var(--vf-color-border)",
    panelBackground: "var(--vf-color-surface)",
    panelColor: "var(--vf-color-text)",
    panelSubtleBackground: "transparent",
    tableBorderColor: "var(--vf-color-border)",
    tableBackground: "var(--vf-color-surface)",
    tableColor: "var(--vf-color-text)",
    tableCaptionColor: "var(--vf-color-muted)",
    tableHeadBackground: "var(--vf-color-surface-muted)",
    tableHeadColor: "var(--vf-color-text)",
    tableFootBackground:
      "color-mix(in srgb, var(--vf-color-surface) 88%, var(--vf-color-surface-muted))",
    tableFootColor: "var(--vf-color-muted)",
    tableStripeBackground:
      "color-mix(in srgb, var(--vf-color-surface) 78%, var(--vf-color-surface-muted))",
    dialogContentBorderColor: "var(--vf-color-border)",
    dialogContentBackground: "var(--vf-color-surface)",
    dialogContentColor: "var(--vf-color-text)",
    dialogContentFocusBorderColor: "var(--vf-color-primary)",
    dialogDividerColor: "var(--vf-divider-color)",
    dialogHeaderMinHeight: "4rem",
    dialogFooterMinHeight: "4rem",
    drawerContentBorderColor: "var(--vf-color-border)",
    drawerContentBackground: "var(--vf-color-surface)",
    drawerContentColor: "var(--vf-color-text)",
    drawerContentFocusBorderColor: "var(--vf-color-primary)",
    drawerDividerColor: "var(--vf-divider-color)",
    drawerHeaderMinHeight: "4rem",
    drawerFooterMinHeight: "4rem",
    popoverTriggerFocusBorderColor: "var(--vf-color-primary)",
    popoverContentBorderColor: "var(--vf-color-border)",
    popoverContentBackground: "var(--vf-color-surface)",
    popoverContentColor: "var(--vf-color-text)",
    tooltipContentBorderColor: "var(--vf-color-border)",
    tooltipContentBackground: "var(--vf-color-surface)",
    tooltipContentColor: "var(--vf-color-text)",
    textBodyFontSize: "var(--vf-font-size-xl)",
    textBodyLineHeight: "var(--vf-line-height-normal)",
    textBodyFontWeight: "var(--vf-font-weight-regular)",
    textCaptionFontSize: "var(--vf-font-size-sm)",
    textCaptionLineHeight: "var(--vf-line-height-normal)",
    textCaptionFontWeight: "var(--vf-font-weight-medium)",
    textLabelFontSize: "var(--vf-font-size-md)",
    textLabelLineHeight: "var(--vf-line-height-tight)",
    textLabelFontWeight: "var(--vf-font-weight-medium)",
    headingFontSizeSm: "var(--vf-font-size-lg)",
    headingFontSizeMd: "var(--vf-font-size-xl)",
    headingFontSizeLg: "var(--vf-font-size-2xl)",
    headingFontSizeXl: "var(--vf-font-size-3xl)",
    headingFontWeight: "var(--vf-font-weight-semibold)",
    buttonSecondaryHoverBackground:
      "color-mix(in srgb, var(--vf-color-surface-muted) 94%, var(--vf-color-text))",
    buttonSecondaryHoverBorderColor: "var(--vf-color-border)",
    buttonSecondaryActiveBackground:
      "color-mix(in srgb, var(--vf-color-surface-muted) 90%, var(--vf-color-text))",
    buttonSecondaryActiveBorderColor: "var(--vf-color-border)",
    buttonGhostHoverBackground:
      "color-mix(in srgb, var(--vf-color-primary) 8%, var(--vf-color-surface))",
    buttonGhostHoverBorderColor: "transparent",
    buttonGhostActiveBackground:
      "color-mix(in srgb, var(--vf-color-primary) 14%, var(--vf-color-surface))",
    buttonGhostActiveBorderColor: "transparent",
    buttonSolidHoverFilter: "brightness(0.95) saturate(1.03)",
    buttonSolidActiveFilter: "brightness(0.9) saturate(1.04)",
    fieldBackground: "var(--vf-color-surface)",
    fieldBorderColor: "var(--vf-color-border)",
    fieldHoverBorderColor: "var(--vf-color-primary-border-soft)",
    fieldFocusBorderColor: "var(--vf-color-primary)",
    fieldInvalidBorderColor: "var(--vf-color-danger)",
    fieldDisabledBackground: "var(--vf-color-surface-muted)",
    fieldDisabledColor: "var(--vf-color-muted)",
    fieldPlaceholderColor: "var(--vf-color-muted)",
    inputBackground: "var(--vf-field-background)",
    inputBorderColor: "var(--vf-field-border-color)",
    inputHoverBorderColor: "var(--vf-field-hover-border-color)",
    inputFocusBorderColor: "var(--vf-field-focus-border-color)",
    inputInvalidBorderColor: "var(--vf-field-invalid-border-color)",
    inputDisabledBackground: "var(--vf-field-disabled-background)",
    inputColor: "var(--vf-color-text)",
    inputDisabledColor: "var(--vf-field-disabled-color)",
    inputPlaceholderColor: "var(--vf-field-placeholder-color)",
    textareaBackground: "var(--vf-field-background)",
    textareaBorderColor: "var(--vf-field-border-color)",
    textareaHoverBorderColor: "var(--vf-field-hover-border-color)",
    textareaFocusBorderColor: "var(--vf-field-focus-border-color)",
    textareaInvalidBorderColor: "var(--vf-field-invalid-border-color)",
    textareaDisabledBackground: "var(--vf-field-disabled-background)",
    textareaColor: "var(--vf-color-text)",
    textareaDisabledColor: "var(--vf-field-disabled-color)",
    textareaPlaceholderColor: "var(--vf-field-placeholder-color)",
    selectBackground: "var(--vf-field-background)",
    selectBorderColor: "var(--vf-field-border-color)",
    selectHoverBorderColor: "var(--vf-field-hover-border-color)",
    selectFocusBorderColor: "var(--vf-field-focus-border-color)",
    selectInvalidBorderColor: "var(--vf-field-invalid-border-color)",
    selectDisabledBackground: "var(--vf-field-disabled-background)",
    selectColor: "var(--vf-color-text)",
    selectDisabledColor: "var(--vf-field-disabled-color)",
    selectPlaceholderColor: "var(--vf-field-placeholder-color)",
    selectIconColor: "var(--vf-color-muted)",
    selectDisabledIconColor: "var(--vf-field-disabled-color)",
    selectionControlBackground:
      "color-mix(in srgb, var(--vf-color-border) 12%, var(--vf-color-surface))",
    selectionControlBorderColor: "var(--vf-color-border)",
    selectionControlHoverBorderColor: "var(--vf-color-primary-border-soft)",
    selectionControlFocusBorderColor: "var(--vf-color-primary)",
    selectionControlInvalidBorderColor: "var(--vf-color-danger)",
    selectionControlDisabledBackground: "var(--vf-color-surface-muted)",
    selectionControlDisabledBorderColor: "var(--vf-color-border)",
    selectionControlDisabledColor: "var(--vf-color-muted)",
    checkboxBackground: "var(--vf-selection-control-background)",
    checkboxBorderColor: "var(--vf-selection-control-border-color)",
    checkboxHoverBorderColor: "var(--vf-selection-control-hover-border-color)",
    checkboxFocusBorderColor: "var(--vf-selection-control-focus-border-color)",
    checkboxInvalidBorderColor:
      "var(--vf-selection-control-invalid-border-color)",
    checkboxCheckedBackground: "var(--vf-color-primary)",
    checkboxCheckedBorderColor: "var(--vf-color-primary)",
    checkboxMarkColor: "var(--vf-color-primary-contrast)",
    checkboxDisabledBackground:
      "var(--vf-selection-control-disabled-background)",
    checkboxDisabledBorderColor:
      "var(--vf-selection-control-disabled-border-color)",
    checkboxDisabledColor: "var(--vf-selection-control-disabled-color)",
    checkboxDisabledMarkColor: "var(--vf-selection-control-disabled-color)",
    radioControlBackground: "var(--vf-selection-control-background)",
    radioHoverBorderColor: "var(--vf-selection-control-hover-border-color)",
    radioBorderColor: "var(--vf-selection-control-border-color)",
    radioFocusBorderColor: "var(--vf-selection-control-focus-border-color)",
    radioInvalidBorderColor: "var(--vf-selection-control-invalid-border-color)",
    radioCheckedBorderColor: "var(--vf-color-primary)",
    radioDotColor: "var(--vf-color-primary)",
    radioDisabledBackground: "var(--vf-selection-control-disabled-background)",
    radioDisabledBorderColor:
      "var(--vf-selection-control-disabled-border-color)",
    radioDisabledColor: "var(--vf-selection-control-disabled-color)",
    radioDisabledDotColor: "var(--vf-selection-control-disabled-color)",
    switchTrackBorderColor: "var(--vf-selection-control-border-color)",
    switchTrackHoverBorderColor:
      "var(--vf-selection-control-hover-border-color)",
    switchTrackFocusBorderColor:
      "var(--vf-selection-control-focus-border-color)",
    switchTrackCheckedBorderColor: "var(--vf-color-primary)",
    switchTrackCheckedHoverBorderColor: "var(--vf-color-primary)",
    switchTrackInvalidBorderColor:
      "var(--vf-selection-control-invalid-border-color)",
    switchTrackStaticBorderColor: "var(--vf-selection-control-border-color)",
    switchTrackDisabledBackground:
      "var(--vf-selection-control-disabled-background)",
    switchTrackDisabledBorderColor:
      "var(--vf-selection-control-disabled-border-color)",
    switchDisabledColor: "var(--vf-selection-control-disabled-color)",
    switchTrackBackground: "var(--vf-radio-control-background)",
    switchTrackHoverBackground:
      "color-mix(in srgb, var(--vf-color-text) 12%, var(--vf-color-surface))",
    switchTrackCheckedBackground: "var(--vf-color-primary)",
    switchTrackCheckedHoverBackground:
      "color-mix(in srgb, var(--vf-color-primary) 92%, var(--vf-color-surface))",
    switchThumbBackground:
      "color-mix(in srgb, var(--vf-color-text) 82%, var(--vf-color-surface))",
    switchThumbBorderColor: "var(--vf-switch-thumb-background)",
    switchThumbShadow: "none",
    switchThumbColor:
      "color-mix(in srgb, var(--vf-color-surface) 88%, transparent)",
    switchThumbIconSize: "0.75rem",
    switchThumbDisabledBackground: "var(--vf-switch-thumb-background)",
    switchThumbDisabledBorderColor:
      "var(--vf-switch-thumb-disabled-background)",
    switchThumbDisabledColor: "var(--vf-switch-thumb-color)",
    switchThumbCheckedBackground: "var(--vf-color-surface)",
    switchThumbCheckedBorderColor: "var(--vf-switch-thumb-checked-background)",
    switchThumbCheckedShadow: "none",
    switchThumbCheckedColor:
      "color-mix(in srgb, var(--vf-color-text) 82%, transparent)",
    switchThumbInverseBackground: "var(--vf-color-surface)",
    switchThumbInverseBorderColor: "var(--vf-color-border)",
    switchThumbInverseColor: "var(--vf-color-text)",
    proseHeadingMargin: "1.5em",
    proseHeadingGap: "0.5em",
    proseBlockSpacing: "1em",
    proseListPaddingInlineStart: "1.5em",
    proseListItemSpacing: "0.375em",
    proseLinkHoverColor:
      "color-mix(in srgb, var(--vf-color-primary) 82%, var(--vf-color-text))",
    proseBlockquotePaddingInlineStart: "1rem",
    proseBlockquoteBorderWidth: "3px",
    proseInlineCodeFontSize: "0.95em",
    proseInlineCodePadding: "0.125rem 0.375rem",
    proseCodeBlockPadding: "0.75rem 1rem",
    proseHrMargin: "1.5rem",
    colorBg: "#f6f8fb",
    colorSurface: "#ffffff",
    colorSurfaceMuted: "#f3f3f3",
    colorText: "#1f232b",
    colorMuted: "#616773",
    colorBorder: "#d9dde3",
    colorPrimary: "#0e639c",
    colorPrimaryContrast: "#ffffff",
    colorPrimarySoft:
      "color-mix(in srgb, var(--vf-color-primary) 12%, var(--vf-color-surface))",
    colorPrimaryBorderSoft:
      "color-mix(in srgb, var(--vf-color-primary) 22%, var(--vf-color-border))",
    colorFocusRing:
      "color-mix(in srgb, var(--vf-color-primary) 32%, var(--vf-color-surface))",
    colorSuccess: "#2e7d32",
    colorSuccessContrast: "#ffffff",
    colorInfo: "#0069ba",
    colorInfoContrast: "#ffffff",
    colorWarn: "#9f8400",
    colorWarnContrast: "#1f1300",
    colorHelp: "#7245ae",
    colorHelpContrast: "#ffffff",
    colorDanger: "#c72e39",
    colorDangerContrast: "#ffffff",
    colorContrast: "#252526",
    colorContrastContrast: "#ffffff",
    colorSuccessSoft:
      "color-mix(in srgb, var(--vf-color-success) 12%, var(--vf-color-surface))",
    colorInfoSoft:
      "color-mix(in srgb, var(--vf-color-info) 12%, var(--vf-color-surface))",
    colorWarnSoft:
      "color-mix(in srgb, var(--vf-color-warn) 12%, var(--vf-color-surface))",
    colorHelpSoft:
      "color-mix(in srgb, var(--vf-color-help) 12%, var(--vf-color-surface))",
    colorDangerSoft:
      "color-mix(in srgb, var(--vf-color-danger) 12%, var(--vf-color-surface))",
    colorContrastSoft:
      "color-mix(in srgb, var(--vf-color-contrast) 10%, var(--vf-color-surface))",
    colorSuccessBorderSoft:
      "color-mix(in srgb, var(--vf-color-success) 24%, var(--vf-color-border))",
    colorInfoBorderSoft:
      "color-mix(in srgb, var(--vf-color-info) 24%, var(--vf-color-border))",
    colorWarnBorderSoft:
      "color-mix(in srgb, var(--vf-color-warn) 24%, var(--vf-color-border))",
    colorHelpBorderSoft:
      "color-mix(in srgb, var(--vf-color-help) 24%, var(--vf-color-border))",
    colorDangerBorderSoft:
      "color-mix(in srgb, var(--vf-color-danger) 24%, var(--vf-color-border))",
    colorContrastBorderSoft:
      "color-mix(in srgb, var(--vf-color-contrast) 24%, var(--vf-color-border))",
    focusRingWidth: "3px",
    radius: "0.75rem",
    radiusControl: "calc(var(--vf-radius) - 0.125rem)",
    radiusControlTight: "calc(var(--vf-radius) - 0.25rem)",
    radiusSurface: "var(--vf-radius)",
    radiusOverlay: "calc(var(--vf-radius) + 0.125rem)",
    ...breakpointTokens,
    controlHeightSm: "1.75rem",
    controlHeightMd: "2.25rem",
    controlHeightLg: "2.5rem",
    controlFontSizeSm: "var(--vf-text-label-font-size)",
    controlFontSizeMd: "var(--vf-text-body-font-size)",
    controlFontSizeLg: "var(--vf-font-size-xl)",
    buttonPaddingSm: "0.25rem 0.5rem",
    buttonPaddingMd: "0.3125rem 0.75rem",
    buttonPaddingLg: "0.5rem 1rem",
    buttonGap: "0.5rem",
    fieldPaddingSm: "0.25rem 0.5rem",
    fieldPaddingMd: "0.3125rem 0.75rem",
    fieldPaddingLg: "0.5rem 1rem",
    checkboxSizeSm: "1.125rem",
    checkboxSizeMd: "1.25rem",
    checkboxSizeLg: "1.375rem",
    selectionGap: "0.75rem",
    checkboxMarkWidth: "0.25rem",
    checkboxMarkHeight: "0.5rem",
    checkboxMarkStrokeWidth: "2px",
    checkboxMarkOffsetY: "-0.0625rem",
    radioDotSize: "0.5rem",
    switchWidthSm: "2.125rem",
    switchWidthMd: "2.375rem",
    switchWidthLg: "2.625rem",
    switchHeightSm: "1.25rem",
    switchHeightMd: "1.375rem",
    switchHeightLg: "1.5rem",
    switchThumbSizeSm: "0.875rem",
    switchThumbSizeMd: "1rem",
    switchThumbSizeLg: "1.125rem",
    switchThumbInset: "0.125rem",
    textareaMinHeightSm: "4.5rem",
    textareaMinHeightMd: "6rem",
    textareaMinHeightLg: "7rem",
    overlayPadding: "1rem",
    overlayGap: "0.75rem",
    overlayViewportPadding: "1rem",
    menuPadding: "0.5rem",
    menuGap: "0.25rem",
    menuMinWidth: "12rem",
    surfacePadding: "1rem",
    surfaceGap: "0.75rem",
    surfacePaddingCompact: "0.75rem",
    surfaceGapCompact: "0.5rem",
    sectionPadding: "0.75rem 1rem",
    sectionGap: "0.75rem",
    tabsGap: "0.75rem",
    tabsListGap: "0.25rem",
    tabsListPadding: "0.25rem",
    tabsTabPaddingInline: "0.75rem",
    tabsPanelPaddingTop: "0.75rem",
    navMenuListGap: "0.25rem",
    navMenuNestedGap: "0.25rem",
    navMenuCollapseOffsetTop: "0.25rem",
    navMenuCollapseInsetLevel0Margin: "0.5rem",
    navMenuCollapseInsetLevel0Padding: "0.5rem",
    navMenuCollapseInsetSimpleLevel0Margin: "0.5rem",
    navMenuCollapseInsetSimpleLevel0Padding: "0.5rem",
    navMenuCollapseInsetDeepMargin: "0.5rem",
    navMenuCollapseInsetDeepPadding: "0.5rem",
    navMenuCollapseInsetSimpleDeepMargin: "0.5rem",
    navMenuCollapseInsetSimpleDeepPadding: "0.5rem",
    navMenuNodeGroupSpacing: "0.25rem",
    navMenuGroupPadding: "0.375rem 0.75rem",
    navMenuGroupFontSize: "var(--vf-text-label-font-size)",
    navMenuItemPadding: "0.25rem 0",
    navMenuItemGap: "0.5rem",
    navMenuLeadingIconSize: "1rem",
    navMenuLeadingIconColumnSize: "1.25rem",
    tableOfContentsGap: "0.25rem",
    tableOfContentsListGap: "var(--vf-nav-menu-list-gap)",
    tableOfContentsTitleFontSize: "var(--vf-text-caption-font-size)",
    tableOfContentsTitleColor: "var(--vf-color-muted)",
    tableOfContentsItemPadding: "0.25rem 0",
    tableOfContentsLevelStep:
      "calc(var(--vf-nav-menu-collapse-inset-simple-level-0-margin) + var(--vf-nav-menu-collapse-inset-simple-level-0-padding))",
    tableOfContentsColor: "var(--vf-color-text)",
    tableOfContentsHoverColor: "var(--vf-selectable-hover-color)",
    tableOfContentsHoverBackground: "var(--vf-selectable-hover-background)",
    tableOfContentsActiveColor: "var(--vf-selectable-active-color)",
    tableOfContentsActiveBackground: "transparent",
    badgeHeight: "1.375rem",
    badgePadding: "0.0625rem 0.25rem",
    badgeGap: "0.25rem",
    badgeRadius: "var(--vf-radius-control-tight)",
    badgeFontSize: "var(--vf-text-label-font-size)",
    badgeLineHeight: "var(--vf-text-label-line-height)",
    tagHeight: "1.5rem",
    tagPadding: "0.125rem 0.3125rem",
    tagFontSize: "var(--vf-text-label-font-size)",
    tagLineHeight: "var(--vf-text-label-line-height)",
    tooltipPadding: "0.5rem 0.75rem",
    tooltipMaxWidth: "16rem",
    tooltipFontSize: "var(--vf-text-body-font-size)",
    tooltipLineHeight: "var(--vf-text-body-line-height)",
    dialogWidthSm: "28rem",
    dialogWidthMd: "36rem",
    dialogWidthLg: "48rem",
    dialogMaxHeight: "min(85vh, 48rem)",
    drawerSizeSm: "20rem",
    drawerSizeMd: "26rem",
    drawerSizeLg: "32rem",
    drawerOffsetTop: "0px",
    drawerBodyPadding: "var(--vf-overlay-padding)",
    dialogTitleFontSize: "var(--vf-text-body-font-size)",
    dialogHeaderGap: "0.75rem",
    dialogActionsGap: "0.5rem",
    popoverWidth: "min(100vw - 2rem, 22rem)",
    floatingArrowSize: "0.625rem",
    overlayBackdrop: "rgba(0, 0, 0, 0.44)",
    alertPrimarySoft:
      "color-mix(in srgb, var(--vf-color-primary) 8%, var(--vf-color-surface))",
    alertPrimaryBorderSoft:
      "color-mix(in srgb, var(--vf-color-primary) 22%, var(--vf-color-border))",
    alertContentGap: "0.25rem",
    alertTitleFontSize: "var(--vf-text-body-font-size)",
    cardTitleFontSize: "var(--vf-text-body-font-size)",
    panelTitleFontSize: "var(--vf-text-body-font-size)",
    motionDurationFast: vfMotionTokens.durationFast,
    motionDurationNormal: vfMotionTokens.durationNormal,
    motionEaseStandard: vfMotionTokens.easeStandard,
    zOverlay: "1000",
    zDrawer: "1000",
    zDropdown: "900",
    zPopover: "925",
    zTooltip: "950",
    spacing: "1rem",
    shadow: "none",
  },
  dark: {
    colorBg: "#1e1e1e",
    colorSurface: "#252526",
    colorSurfaceMuted: "#2d2d30",
    colorText: "#d4d4d4",
    colorMuted: "#9da0a6",
    colorBorder: "#3c3c3c",
    colorPrimary: "#2f7fd6",
    colorPrimaryContrast: "#ffffff",
    colorPrimarySoft:
      "color-mix(in srgb, var(--vf-color-primary) 12%, var(--vf-color-surface))",
    colorPrimaryBorderSoft:
      "color-mix(in srgb, var(--vf-color-primary) 22%, var(--vf-color-border))",
    colorFocusRing:
      "color-mix(in srgb, var(--vf-color-primary) 32%, var(--vf-color-surface))",
    colorSuccess: "#3f8746",
    colorSuccessContrast: "#ffffff",
    colorInfo: "#1f76be",
    colorInfoContrast: "#ffffff",
    colorWarn: "#c6a25f",
    colorWarnContrast: "#1f1300",
    colorHelp: "#8553a1",
    colorHelpContrast: "#ffffff",
    colorDanger: "#bf3f3f",
    colorDangerContrast: "#ffffff",
    colorContrast: "#d7d7d7",
    colorContrastContrast: "#111827",
    colorSuccessSoft:
      "color-mix(in srgb, var(--vf-color-success) 12%, var(--vf-color-surface))",
    colorInfoSoft:
      "color-mix(in srgb, var(--vf-color-info) 12%, var(--vf-color-surface))",
    colorWarnSoft:
      "color-mix(in srgb, var(--vf-color-warn) 12%, var(--vf-color-surface))",
    colorHelpSoft:
      "color-mix(in srgb, var(--vf-color-help) 12%, var(--vf-color-surface))",
    colorDangerSoft:
      "color-mix(in srgb, var(--vf-color-danger) 12%, var(--vf-color-surface))",
    colorContrastSoft:
      "color-mix(in srgb, var(--vf-color-contrast) 10%, var(--vf-color-surface))",
    colorSuccessBorderSoft:
      "color-mix(in srgb, var(--vf-color-success) 24%, var(--vf-color-border))",
    colorInfoBorderSoft:
      "color-mix(in srgb, var(--vf-color-info) 24%, var(--vf-color-border))",
    colorWarnBorderSoft:
      "color-mix(in srgb, var(--vf-color-warn) 24%, var(--vf-color-border))",
    colorHelpBorderSoft:
      "color-mix(in srgb, var(--vf-color-help) 24%, var(--vf-color-border))",
    colorDangerBorderSoft:
      "color-mix(in srgb, var(--vf-color-danger) 24%, var(--vf-color-border))",
    colorContrastBorderSoft:
      "color-mix(in srgb, var(--vf-color-contrast) 24%, var(--vf-color-border))",
    switchThumbBackground:
      "color-mix(in srgb, var(--vf-color-text) 82%, var(--vf-color-surface))",
    switchThumbBorderColor: "var(--vf-switch-thumb-background)",
    switchThumbColor:
      "color-mix(in srgb, var(--vf-color-surface) 84%, var(--vf-color-text))",
    switchThumbCheckedBackground:
      "color-mix(in srgb, var(--vf-color-text) 82%, var(--vf-color-surface))",
    switchThumbCheckedBorderColor: "var(--vf-switch-thumb-checked-background)",
    switchThumbCheckedColor:
      "color-mix(in srgb, var(--vf-color-surface) 84%, var(--vf-color-text))",
    switchThumbInverseBackground: "var(--vf-color-bg)",
    switchThumbInverseBorderColor: "var(--vf-color-border)",
    switchThumbInverseColor: "var(--vf-color-text)",
    focusRingWidth: "3px",
    zOverlay: "1000",
    zDrawer: "1000",
    zDropdown: "900",
    zPopover: "925",
    zTooltip: "950",
    shadow: "none",
  },
};
